name: IsabellaCaspari Workflow
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12.x' ]
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}
          
        - name: npm install and npm run build
          run: |
            npm ci 
            npm run build:ci
          
        - name: Copy to isabellacaspari.github.io
          uses: andstor/copycat-action@v3
          with:
            personal_token: ${{ secrets.PERSONAL_TOKEN }}
            dst_branch: master
            src_branch: master
            src_path: docs/.
            dst_path: /.
            dst_owner: IsabellaCaspari
            dst_repo_name: isabellacaspari.github.io
