name: IsabellaCaspari Workflow
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          node-version: [13.x]
    steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Node v13.11.0
          uses: actions/setup-node@v1
          with:
            node-version: v13.11.0

        - name: npm install and npm run build
          run: |
            npm ci 
            npm run build:ci
            
        - name: checkout and push changes to ext repo
          run: |
            git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/IsabellaCaspari/isabellacaspari.github.io target
            rm target
            copy docs target
            git add target
            git commit -m "Automatic publish from github.com/isabellas-angular-app"
            git push target master
